# Generated by Django 3.1.5 on 2021-01-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSchedulePictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=40, verbose_name='Название группы')),
                ('picture_weekend_1', models.CharField(max_length=50, verbose_name='Расписание на 1 неделю')),
                ('picture_weekend_2', models.CharField(max_length=50, verbose_name='Расписание на 2 неделю')),
            ],
            options={
                'db_table': 'bot_schedule_pictures_test',
            },
        ),
        migrations.CreateModel(
            name='BotScheduleUlSTU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=40, verbose_name='Название группы')),
                ('today', models.TextField(verbose_name='Расписание на сегодня')),
                ('tomorrow', models.TextField(verbose_name='Расписание на завтра')),
            ],
            options={
                'db_table': 'bot_schedule_text_test',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='vk_id пользователя')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия пользователя')),
                ('group_name', models.CharField(max_length=40, verbose_name='Название группы')),
            ],
            options={
                'db_table': 'bot_users_test',
                'ordering': ['id'],
            },
        ),
    ]
