# Generated by Django 3.1.5 on 2021-01-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botschedulepictures',
            options={'ordering': ['id'], 'verbose_name': 'Расписание на неделю', 'verbose_name_plural': 'Таблица расписаний на неделю'},
        ),
        migrations.AlterModelOptions(
            name='botscheduleulstu',
            options={'ordering': ['id'], 'verbose_name': 'Расписание на 2 дня', 'verbose_name_plural': 'Таблица расписаний на 2 дня'},
        ),
        migrations.AlterModelOptions(
            name='botusers',
            options={'ordering': ['id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='facultiesulstu',
            options={'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelTable(
            name='botusers',
            table='bot_users',
        ),
    ]
