# Generated by Django 3.1.5 on 2021-01-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='botschedulepictures',
            table='bot_schedule_pictures',
        ),
        migrations.AlterModelTable(
            name='botscheduleulstu',
            table='bot_schedule_text',
        ),
    ]
