# Generated by Django 3.1.5 on 2021-01-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20210121_1258'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='botusers',
            table='bot_users',
        ),
    ]
